### ISSUE TITLE
Incluir Modernizr para compatibilidad con navegadores antiguos

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#25]
Para utilizar sin problema los nuevos tags de HTML5 en navegadores antiguos.

http://modernizr.com/

**Comment by marti1125** [comment]
con vue.js ya no vamos a necesitar esto creo... =?

**Comment by sebastianserna** [comment]
Inicialmente pensé que sería necesario pero por el enfoque experimental de este proyecto y como la idea es utilizar nuevas tecnologías sin limitaciones no daremos soporte a navegadores antiguos.
