### ISSUE TITLE
Integrar require.js

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#31]
Gestionar módulos javascript con require.js para mejorar el rendimiendo.

https://github.com/jrburke/requirejs

**Comment by marti1125** [comment]
@sebastianserna te puedo ayudar =D

**Comment by sebastianserna** [comment]
@marti1125 gracias! de hecho me puedes asesorar bastante, ya que por el momento aún no he decidido que librerías de JavaScript utilizar. Por lo pronto me estoy centrando en el HTML, CSS y JavaScript con JQuery pero es algo que se puede replantear. Ahí tu aporte será muy bien recibido. Estamos en contacto 👍

**Comment by marti1125** [comment]
@sebastianserna genial con gusto en apoyarte mas bien me podrias indicar en que issue en especifico podria empezar =D

**Comment by sebastianserna** [comment]
@marti1125 ahora que vamos a hacer la transición a Vue.js estuve investigando sobre diferentes herramientas para gestionar código Javascript y me encuentro con que [Require.js ya no es tan utilizado](https://www.reddit.com/r/javascript/comments/3azxtj/requirejs_vs_browserify_vs_webpack/), es una suerte de ambiente extraño en este mundo de Javascript donde parece que todo se vuelve obsoleto en cuestión de 2 años jaja

Pero al igual que con Vue.js (más allá de las modas y pensando objetivamente) te quería consultar si ¿es pertinente descartar Require.js (igual no lo hemos implementado) y centrarnos en Browserify o Webpack? la decisión podría estar encaminada en cuál de los dos proyectos se integra mejor con Vue.js y en caso de que esto sea indiferente ¿cuál te parece mejor? ¿has trabajado con alguno de ellos?
- https://webpack.github.io/
- http://browserify.org/

Quedo atento!

Un saludo!

**Comment by marti1125** [comment]
he usado webpack con reactjs para crear proyectos web porque tiene un modulo de autocargado como en gulp browsersync. y te da otras opciones para testing. Creo que para empezar seria con los componentes mas sencillos según las lista que propusistes.

**Comment by sebastianserna** [comment]
De acuerdo. Es todavía prematuro tomar una decisión antes de implementar lo básico. Por mi parte he estado trabajando en un proyecto alterno y no he actualizado el repositorio principal en varios días pero pronto integraré unos cambios importantes para que podamos avanzar.

**Comment by sebastianserna** [comment]
Este issue ya no aplica para este repositorio, queda pendiente crear un nuevo issue en el proyecto [swan-vue](https://github.com/acuariux/swan-vue). En este caso debemos decidir qué herramienta utilizar, sin tener todavía muchos conocimientos me inclinaría por https://webpack.github.io/ @marti1125 ¿qué piensas?

**Comment by sebastianserna** [comment]
Se cierra este issue, en próximos meses el desarrollo del framework se va a concentrar en el código CSS por lo que los issues relacionados con JavaScript se reducirán al mínimo.
