### ISSUE TITLE
Reducir el tamaño de la carpeta node_modules

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#36]
Swan utiliza [Gulp](http://gulpjs.com/) para automatizar ciertas tareas de desarrollo como compilar el código Sass y generar archivos CSS finales listos para producción. Esto es algo muy positivo porque ahorra tiempo valioso de desarrollo. Sin embargo, he observado que la carpeta node_modules tiene un peso de 86MB algo que considero exagerado.

Los módulos y dependencias utilizadas en el proyecto se especifican en el archivo package.json:
https://github.com/acuariux/swan/blob/master/package.json

¿Hay alguna forma de reducir el tamaño de la carpeta node_modules manteniendo los módulos instalados?

**Comment by marti1125** [comment]
Hola @sebastianserna utilizando
sudo npm ddp (es para retirar las dependencias duplicadas)
como sugieren en este post 
http://foundation.zurb.com/forum/posts/39120-huge-node_modules-folder-sizes
https://docs.npmjs.com/cli/dedupe

de los 104mb que tenia lo bajo a 99mb no es mucho pero eso ya dependeria de las dependencias que tiene

http://stackoverflow.com/questions/13318364/how-to-deploy-node-js-application-with-deep-node-modules-structure-on-windows

**Comment by sebastianserna** [comment]
@marti1125 gracias por tu ayuda en la búsqueda de una solución!

Sin embargo, lo que he podido encontrar en muchos foros es que aún no hay una manera contundente de resolver este problema. En otro [hilo relacionado con node_modules](https://discourse.roots.io/t/size-of-node-modules-directory/5006/2) me llamó la atención un comentario del usuario kalenjohnson (al final del hilo):

> There has been a comment or two before about the size of the folder. I suggest looking at it from the perspective of "look at all the stuff that is now automated for me". The bigger the folder is, the more stuff it's doing for you automatically.

¿Qué piensas del anterior comentario? es como resignarse al hecho de que si queremos procesos automatizados hay que aceptar que dicha carpeta sea pesada.

Quedo atento...

**Comment by marti1125** [comment]
@sebastianserna las dependencias cuando lo bajas no solo se baja los js necesarios si que los modulos adentro tienen ejemplos archivos css readme es bajarte todo un proyecto y eso va hacer que la carpeta node_modules sea pesada.
En otro lenguaje es casi lo mismo en java por ejemplo las dependecias podria pesar uff no siempre la gente empaquete lo necesario

**Comment by sebastianserna** [comment]
@marti1125 disculpa la tardanza en responder. Es cierto lo que comentas de otros lenguajes como Java que también utilizan dependencias que ocupan mucho espacio.

Sin embargo, ayer hice una prueba en mi portátil (Mac) actualizando Node.js a la versión 6 que viene con npm 3. Luego de instalado ejecuté el npm install y la carpeta node_modules que antes pesaba 86MB ahora pesa algo más de 50MB. Parece que la nueva versión de npm ayuda en este proceso, pero la verdad debo investigar más. Encontré un [hilo relacionado en Reddit](https://www.reddit.com/r/webdev/comments/42cpjy/why_is_my_node_modules_directory_140mb_is_this/) donde comentan lo siguiente:

> Use npm 3, it stores all of its modules in a flat directory structure (it automatically dedupes when you run npm install)

Un saludo!

**Comment by marti1125** [comment]
@sebastianserna si como mencionas ya las depencias automaticamente ejecutan "dedupes" para que no se repitan las dependencias de otros paquetes.

> damos por cerrado este hilo 👍

**Comment by sebastianserna** [comment]
@marti1125 si, por el momento esa es la solución, con npm 3 se optimiza el peso de la carpeta node_modules.

Hilo cerrado 👍
