### ISSUE TITLE
Reemplazar JQuery? (React, Vue o similares)

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#40]
Es algo que me viene rondando la cabeza desde hace unos meses, no lo digo por seguir una moda específica sino porque en el fondo me gustaría que este framework se pueda utilizar en sitios web sencillos pero también en aplicaciones web, para este último propósito pienso que podría ser interesante utilizar React, pero como no tengo suficiente experiencia en el tema, no sé si (pensando a futuro) sea algo descabellado descartar JQuery desde el comienzo.

¿Qué piensas @marti1125 ?

**Comment by marti1125** [comment]
encontre un contricante para Reactjs jejeje
http://vuejs.org/
http://www.infoworld.com/article/3063615/javascript/vuejs-lead-our-javascript-framework-is-faster-than-react.html

**Comment by sebastianserna** [comment]
No lo conocía, pero lo veo muy interesante y tiene [bastante acogida en Github](https://github.com/vuejs/vue) (con más de 30.000 estrellas, cercano a React). Además me parece relevante el hecho de que Laravel lo haya elegido como framework Javascript por defecto, algo que seguro se reflejará en OctoberCMS proyecto que me gusta bastante:
http://react-etc.net/entry/php-framework-laravel-selects-vue-js-as-default-javascript-framework

También me gusta que sea un proyecto independiente, no de una empresa privada. Voy a explorarlo mejor. Gracias @marti1125 la idea aquí es encontrar una alternativa sólida y tu propuesta pinta muy bien 👍

**Comment by sebastianserna** [comment]
@marti1125 voy a cambiar el título del issue para que sea más abierto a otras alternativas.

**Comment by marti1125** [comment]
@sebastianserna genial! si me parece un interesante framework lo podriamos orientar a eso y crear componentes con vuejs

**Comment by sebastianserna** [comment]
Si, se ve muy bien. Acabo de leer varios artículos sobre Vue y en general tiene muy buenas críticas. @marti1125 una consulta: algo que también me ha llamado la atención de React es el proyecto [React Native](https://facebook.github.io/react-native/) que permite programar aplicaciones nativas iOS y Android con Javascript. Este último punto me parece crucial porque también me interesa mucho el soporte para móviles y la facilidad de tener una versión de Swan "Nativa".

¿Crees que en el proyecto Vue existirá en un futuro algo similar a React Native? sé que es algo difícil de precisar, pero puede que ya exista alguna discusión al respecto.

Un saludo!

**Comment by sebastianserna** [comment]
@marti1125 acabo de encontrar esta discusión al respecto de mi consulta sobre "Vue Native":

**is there any plan for "vue-native"?**
https://github.com/vuejs/vue/issues/2119
En el hilo mencionan el proyecto Weex (que utiliza Vue 2.0) creado por la empresa china Alibaba.

**Weex project**
https://alibaba.github.io/weex/
https://github.com/alibaba/weex

Este proyecto se ve muy bien y tiene una apariencia muy profesional.

¿Cómo te parece?

**Comment by sebastianserna** [comment]
Aquí un artículo interesante sobre el rendimiento de Vue vs React:

**"From a React point of Vue..." - comparing React.js to Vue.js for dynamic tabular data**
https://engineering.footballradar.com/from-a-react-point-of-vue-comparing-reactjs-to-vuejs-for-dynamic-tabular-data/

**Comment by marti1125** [comment]
aunq yo hago apps con cordova. El vue native genera nativo sin usar cordova.
podriamos usar los watchers para las validaciones automaticas de los form http://vuejs.org/guide/computed.html

**Comment by sebastianserna** [comment]
Perfecto @marti1125 entonces estamos los dos de acuerdo en utilizar Vue.js voy a dar por cerrado este issue y estamos en contacto para planear los próximos pasos para implementarlo. Yo tengo pendiente subir una documentación básica sobre el framework y su estructura básica, espero que no pase de la próxima semana. Muchas gracias por tu apoyo!

**Comment by marti1125** [comment]
@sebastianserna listo estarea al tanto =D
