### ISSUE TITLE
Instalar plugin para scroll personalizado

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#8]
Instalar plugin JQuery para personalizar scrollbar.

**Comment by sebastianserna** [comment]
Todavía no logro encontrar un plugin que sea liviano y que no requiera insertar una hoja de estilos con clases propias del plugin. He realizado varias pruebas con Nicescroll pero finalmente lo desinstalé porque es demasiado pesado y entraba en conflicto con JLayout :(

**Comment by sebastianserna** [comment]
Acabo de implementar Nanoscroller y funciona bien por el momento, lo malo es que requiere encerrar el contenido en 2 divs anidados (nano y nano-content) y tiene una hoja de estilos propia que incluí en la estructura de archivos Sass. (Hay que probar a fondo la compatibilidad con los demás módulos).

**Comment by marti1125** [comment]
@sebastianserna la solucion media reyada @_@ es construir nuestro propois componentes basandonos de algun plugin y haciendo la integracion asi como lo hace bootstrap con sus componentes javascript (modal, tabs, tooltip, etc)

**Comment by sebastianserna** [comment]
@marti1125 tienes razón ¿cuál sería la manera más práctica de hacerlo? sería crear nuestros propios plugins para JQuery? o que sean en JavaScript puro sin depender de JQuery?

**Comment by marti1125** [comment]
@sebastianserna disculpa la tardanza... le di un vistazo a los plugins de jquery estamos usando
lo cual esta bien para empezar. porque ahora que lo pienso crear nuestro plugin seria mas trabajoso jejej lo que podemos hacer es:
- una lista de los componentes a usar =?

Que tipos de componentes tienes en mista utilizar =?

**Comment by sebastianserna** [comment]
Esta semana decidimos utilizar [Vue.js](https://vuejs.org/) como libreria Javascript principal en vez de JQuery por lo que he estado investigando sobre Vue y encontré el sitio web [vuejsexamples.com](vuejsexamples.com) que tiene demos de componentes realizados con esta libreria. En este enlace un scroll personalizado:

http://vuejsexamples.com/simplest-scroll-area-component-with-custom-scrollbar-for-vue-js/

**Comment by marti1125** [comment]
Hola @sebastianserna este issue lo cerramos para abrir uno nuevos sobre la implementacion de los componentes utilizando Vue.js
¿Que opinas?

**Comment by sebastianserna** [comment]
De acuerdo, este issue se cierra y puede crearse en el proyecto [swan-vue](https://github.com/acuariux/swan-vue/issues)
